"resources"
{
"maps/ff_grind_dev4.lua" "file"
"maps/ff_grind_dev4.txt" "file"
"maps/ff_grind_dev4.bsp" "file"
"maps/ff_grind_dev4.res" "file"
"materials/vgui/loadingscreens/ff_grind_dev4.vmt" "file"
"materials/vgui/loadingscreens/ff_grind_dev4.vtf" "file"
"materials/skybox/frozenbk.vmt" "file"
"materials/skybox/frozendn.vmt" "file"
"materials/skybox/frozenft.vmt" "file"
"materials/skybox/frozenlf.vmt" "file"
"materials/skybox/frozenrt.vmt" "file"
"materials/skybox/frozenup.vmt" "file"
"materials/skybox/frozenbk.vtf" "file"
"materials/skybox/frozendn.vtf" "file"
"materials/skybox/frozenft.vtf" "file"
"materials/skybox/frozenlf.vtf" "file"
"materials/skybox/frozenrt.vtf" "file"
"materials/skybox/frozenup.vtf" "file"
"materials/ff_grind/suspicious.vtf" "file"
"materials/ff_grind/suspicious.vmt" "file"
}